# Generated by Django 5.1.1 on 2024-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите скан статьи",
                null=True,
                upload_to="blogs/",
                verbose_name="Изображение",
            ),
        ),
    ]
